### ISSUE TITLE
 The "--all-tables" option does not exist.

### ISSUE THREAD

**Issue by trong291990** [tyghaykal/laravel-seeder-generator#22]
I got this problem
`The "--all-tables" option does not exist.`

But in the docs I saw that option

**Comment by tyghaykal** [comment]
Hi @trong291990, thank you for this issue. I've updated the composer minimum requirement and deploy it on version 2.0.2, please remove this package first then reinstall.

1. Remove using `composer remove --dev tyghaykal/laravel-seed-generator`
2. Reinstall using `composer require --dev tyghaykal/laravel-seed-generator`
