### ISSUE TITLE
Please feature for all tables seeding 

### ISSUE THREAD

**Issue by GoodJob** [tyghaykal/laravel-seeder-generator#8]
For me function to seed all tables is needed very much 🫶 Great job with this plugin!

**Comment by tyghaykal** [comment]
I have this feature but still on my backlog, I will create it maybe in the next couple of weeks and I will update on this issue when I release it.

**Comment by GoodJob** [comment]
great news! Waiting for it!! 🙏

**Comment by tyghaykal** [comment]
Hi @GoodJob, I already push a new version (v2.0) of this packages with support table seeding, more info you can see the readme.md.
